name: Java CI with Maven

on:
  pull_request:
    branches:
      - 'development'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Set up JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '8'
          distribution: 'semeru'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package
      - name: View context attributes
          uses: actions/github-script@v6
          with:
            script: console.log(context)
      - name: Labeller
        if: ${{ failure() }}
        - uses: actions/github-script@v6
          with:
            script: |
              github.rest.pulls.dismissReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.repo.pull_number,
                message: "It is a mortal sin to PR a broken build!"
              })
    
    
