name: Java CI with Maven

on:
  pull_request:
    branches:
      - 'development'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Set up JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '8'
          distribution: 'semeru'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package
      - name: View context attributes
        if: ${{ failure() }}
        uses: actions/github-script@v6.4.1
        with:
          script: |
            core.info(context.payload.after);
            core.info(context.payload.pull_request.number);
            core.info(context.repo.owner);
            core.info(context.repo.repo);
            console.log(context);
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
      - name: Labeller
        if: ${{ failure() }}
        uses: actions/github-script@v6.4.1
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              comments: [
                {
                  path: ".",
                }
              ],
              comments: [
                {
                  body: "It is a mortal sin to PR a broken build! :rage:"
                }
              ],
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: true